# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=0.3.0
maven_group=org.cneko
archives_base_name=JustARod
enabled_platforms=fabric,neoforge

# Minecraft Properties
minecraft_version=1.21.1

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
loader_version=0.15.11

# Fabric API (Fabric 上使用原版 Fabric API)
fabric_version=0.116.12+1.21.1
# Forgified Fabric API (NeoForge 上提供 Fabric API)
forgified_fabric_api_version=0.116.15+2.3.4+1.21.1

# NeoForge
neoforge_version=21.1.248

# Kotlin for Forge (NeoForge 上的 Kotlin 运行时)
kotlin_for_forge_version=5.12.0

# Dependencies
toneko_version=1.9.2
# toNeko NeoForge 版本在 Modrinth Maven 上的版本号（toneko-neoforge-1.9.2）
toneko_neoforge_version=ytAtEo73
geckolib_version=4.8.3
player_animator_version=2.0.4+1.21.1
