modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CSneko/JustARod/issues"
license = "GPL-3.0"

[[mods]]
modId = "justarod"
version = "${version}"
displayName = "JustARod"
authors = "CrystalNeko"
description = '''
meow
'''
logoFile = "assets/justarod/icon.png"

[[dependencies.justarod]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justarod]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"

# Forgified Fabric API 在 NeoForge 上提供 Fabric API
[[dependencies.justarod]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

# Kotlin 运行时（Kotlin for Forge）
[[dependencies.justarod]]
modId = "kotlinforforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.justarod]]
modId = "geckolib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.justarod]]
modId = "toneko"
type = "required"
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"

# 帕秋莉手册（可选联动：安装后可获得指南书并阅读）
[[dependencies.justarod]]
modId = "patchouli"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "justarod.mixins.json"
